// Copyright (c) 2026 The B3Coin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.
//
// Commit 2 of the Modern PoS V1 finality plan: the consensus BLS wrapper.
//
// Independent vectors: the Ethereum bls12-381-tests suite (v0.1.2, JSON),
// embedded as test/data/bls12_381_eth_vectors.json — sign, verify,
// aggregate, fast_aggregate_verify, G1/G2 deserialization (infinity,
// non-canonical, off-curve, wrong subgroup, wrong lengths). Those vectors
// use the same ciphersuite B3 freezes (BLS_SIG_BLS12381G2_XMD:SHA-256_
// SSWU_RO_POP_, G1 keys, G2 signatures). B3 deliberately REJECTS infinity
// points at decode (Ethereum rejects them at verification time); every
// place where that divergence shows is asserted explicitly below.
//
// Proof-of-possession vectors (POP_DST) are generated by this wrapper and
// pinned; the PoP path is the same sign/verify primitive with the POP DST
// over the compressed key, so its correctness is inherited from the
// independently-checked primitive, and the pins freeze the B3 behaviour.

#include <crypto/bls.h>
#include <test/data/bls12_381_eth_vectors.json.h>
#include <test/util/json.h>
#include <univalue.h>
#include <util/strencodings.h>

#include <boost/test/unit_test.hpp>

#include <array>
#include <optional>
#include <string>
#include <type_traits>
#include <vector>

namespace {

std::vector<unsigned char> HexBytes(std::string s)
{
    if (s.rfind("0x", 0) == 0) s = s.substr(2);
    return ParseHex(s);
}

std::string ToHex(std::span<const unsigned char> b) { return HexStr(b); }

std::optional<bls::SecretKey> KeyFromIndex(const unsigned i)
{
    std::array<unsigned char, 32> ikm{};
    ikm[0] = static_cast<unsigned char>(i);
    ikm[1] = static_cast<unsigned char>(i >> 8);
    ikm[31] = 0x42;
    return bls::SecretKey::FromIKM(ikm);
}

} // namespace

BOOST_AUTO_TEST_SUITE(bls_tests)

// VerifiedPublicKey has exactly two construction paths (FromPoP, and the
// validated-chain reconstruction path) and no public constructor: a raw
// PublicKey can never be promoted implicitly.
static_assert(!std::is_default_constructible_v<bls::VerifiedPublicKey>);
static_assert(!std::is_constructible_v<bls::VerifiedPublicKey, const bls::PublicKey&>);
static_assert(!std::is_constructible_v<bls::VerifiedPublicKey, bls::PublicKey>);
static_assert(!std::is_convertible_v<bls::PublicKey, bls::VerifiedPublicKey>);

BOOST_AUTO_TEST_CASE(frozen_scheme_parameters)
{
    BOOST_CHECK_EQUAL(bls::PUBKEY_SIZE, 48u);
    BOOST_CHECK_EQUAL(bls::SIGNATURE_SIZE, 96u);
    BOOST_CHECK_EQUAL(bls::SECRET_SIZE, 32u);
    BOOST_CHECK_EQUAL(bls::DIGEST_SIZE, 32u);
    BOOST_CHECK_EQUAL(bls::SIG_DST, "BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_");
    BOOST_CHECK_EQUAL(bls::POP_DST, "BLS_POP_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_");
    BOOST_CHECK(bls::SIG_DST != bls::POP_DST);
}

BOOST_AUTO_TEST_CASE(eth_vectors_sign)
{
    const UniValue doc = read_json(json_tests::bls12_381_eth_vectors);
    const UniValue& all = doc[0];
    const UniValue& cases = all["sign"];
    BOOST_REQUIRE(cases.isArray() && cases.size() >= 9);
    for (size_t i = 0; i < cases.size(); ++i) {
        const UniValue& c = cases[i];
        const std::string name = c["name"].get_str();
        const auto sk_bytes = HexBytes(c["input"]["privkey"].get_str());
        const auto msg = HexBytes(c["input"]["message"].get_str());
        const auto sk = bls::SecretKey::FromBytes(sk_bytes);
        if (c["output"].isNull()) {
            // zero private key: must be rejected at construction
            BOOST_CHECK_MESSAGE(!sk.has_value(), name);
            continue;
        }
        BOOST_REQUIRE_MESSAGE(sk.has_value(), name);
        BOOST_REQUIRE_MESSAGE(msg.size() == 32, name);
        const bls::Signature sig = sk->Sign(msg);
        BOOST_CHECK_MESSAGE(ToHex(sig.Compressed()) == HexStr(HexBytes(c["output"].get_str())), name);
        // and it verifies under the derived public key
        BOOST_CHECK_MESSAGE(bls::Verify(sk->GetPublicKey(), msg, sig), name);
    }
}

BOOST_AUTO_TEST_CASE(eth_vectors_verify)
{
    const UniValue doc = read_json(json_tests::bls12_381_eth_vectors);
    const UniValue& all = doc[0];
    const UniValue& cases = all["verify"];
    BOOST_REQUIRE(cases.isArray() && cases.size() >= 20);
    size_t checked{0};
    for (size_t i = 0; i < cases.size(); ++i) {
        const UniValue& c = cases[i];
        const std::string name = c["name"].get_str();
        const bool expected = c["output"].get_bool();
        const auto pk = bls::PublicKey::Decode(HexBytes(c["input"]["pubkey"].get_str()));
        const auto sig = bls::Signature::Decode(HexBytes(c["input"]["signature"].get_str()));
        const auto msg = HexBytes(c["input"]["message"].get_str());
        // A vector that Ethereum marks false because of an infinity/invalid key or
        // signature fails at B3's decode step; a true vector must decode.
        if (!pk || !sig || msg.size() != 32) {
            BOOST_CHECK_MESSAGE(!expected, name);
            continue;
        }
        BOOST_CHECK_MESSAGE(bls::Verify(*pk, msg, *sig) == expected, name);
        ++checked;
    }
    BOOST_CHECK_GE(checked, 10u);
}

BOOST_AUTO_TEST_CASE(eth_vectors_deserialization)
{
    const UniValue doc = read_json(json_tests::bls12_381_eth_vectors);
    const UniValue& all = doc[0];
    for (const char* cat : {"deserialization_G1", "deserialization_G2"}) {
        const UniValue& cases = all[cat];
        BOOST_REQUIRE(cases.isArray() && cases.size() >= 10);
        for (size_t i = 0; i < cases.size(); ++i) {
            const UniValue& c = cases[i];
            const std::string name = c["name"].get_str();
            const bool eth_ok = c["output"].get_bool();
            const bool is_infinity_case = name.find("succeeds_infinity") != std::string::npos;
            bool ours;
            if (std::string(cat) == "deserialization_G1") {
                ours = bls::PublicKey::Decode(HexBytes(c["input"]["pubkey"].get_str())).has_value();
            } else {
                ours = bls::Signature::Decode(HexBytes(c["input"]["signature"].get_str())).has_value();
            }
            if (is_infinity_case) {
                // Ethereum decodes infinity; B3 REJECTS it (frozen rule).
                BOOST_CHECK_MESSAGE(eth_ok && !ours, name);
            } else {
                BOOST_CHECK_MESSAGE(ours == eth_ok, name);
            }
        }
    }
}

BOOST_AUTO_TEST_CASE(eth_vectors_aggregate_and_fast_aggregate_verify)
{
    const UniValue doc = read_json(json_tests::bls12_381_eth_vectors);
    const UniValue& all = doc[0];
    {
        const UniValue& cases = all["aggregate"];
        BOOST_REQUIRE(cases.isArray() && cases.size() >= 5);
        for (size_t i = 0; i < cases.size(); ++i) {
            const UniValue& c = cases[i];
            const std::string name = c["name"].get_str();
            std::vector<bls::Signature> sigs;
            bool all_decoded{true};
            for (size_t k = 0; k < c["input"].size(); ++k) {
                const auto s = bls::Signature::Decode(HexBytes(c["input"][k].get_str()));
                if (!s) { all_decoded = false; break; }
                sigs.push_back(*s);
            }
            const auto agg = sigs.empty() || !all_decoded ? std::nullopt : bls::AggregateSignatures(sigs);
            if (c["output"].isNull()) {
                BOOST_CHECK_MESSAGE(!agg.has_value(), name); // empty input
            } else if (name == "aggregate_infinity_signature") {
                // Ethereum aggregates the infinity point to itself; B3 rejects infinity at decode.
                BOOST_CHECK_MESSAGE(!all_decoded, name);
            } else {
                BOOST_REQUIRE_MESSAGE(agg.has_value(), name);
                BOOST_CHECK_MESSAGE(ToHex(agg->Compressed()) == HexStr(HexBytes(c["output"].get_str())), name);
            }
        }
    }
    {
        const UniValue& cases = all["fast_aggregate_verify"];
        BOOST_REQUIRE(cases.isArray() && cases.size() >= 10);
        size_t positive{0};
        for (size_t i = 0; i < cases.size(); ++i) {
            const UniValue& c = cases[i];
            const std::string name = c["name"].get_str();
            const bool expected = c["output"].get_bool();
            std::vector<bls::VerifiedPublicKey> keys;
            bool all_decoded{true};
            for (size_t k = 0; k < c["input"]["pubkeys"].size(); ++k) {
                const auto pk = bls::PublicKey::Decode(HexBytes(c["input"]["pubkeys"][k].get_str()));
                if (!pk) { all_decoded = false; break; }
                // The Ethereum vectors carry no PoPs; the keys are well-formed
                // group elements, so admit them through the explicit trusted path.
                keys.push_back(bls::VerifiedPublicKey::TrustedFromValidatedChain(*pk));
            }
            const auto sig = bls::Signature::Decode(HexBytes(c["input"]["signature"].get_str()));
            const auto msg = HexBytes(c["input"]["message"].get_str());
            if (!all_decoded || !sig || keys.empty() || msg.size() != 32) {
                BOOST_CHECK_MESSAGE(!expected, name);
                continue;
            }
            BOOST_CHECK_MESSAGE(bls::FastAggregateVerify(keys, msg, *sig) == expected, name);
            if (expected) ++positive;
        }
        BOOST_CHECK_GE(positive, 2u);
    }
}

BOOST_AUTO_TEST_CASE(decode_rules_canonical_subgroup_infinity_lengths)
{
    const auto sk = KeyFromIndex(1);
    BOOST_REQUIRE(sk.has_value());
    const bls::PublicKey pk = sk->GetPublicKey();
    const auto bytes = pk.Compressed();
    // wrong lengths
    BOOST_CHECK(!bls::PublicKey::Decode(std::span<const unsigned char>(bytes.data(), 47)).has_value());
    std::vector<unsigned char> longer(bytes.begin(), bytes.end());
    longer.push_back(0);
    BOOST_CHECK(!bls::PublicKey::Decode(longer).has_value());
    // infinity encodings (compressed flag + infinity flag, zero x)
    std::vector<unsigned char> inf_pk(48, 0);
    inf_pk[0] = 0xc0;
    BOOST_CHECK(!bls::PublicKey::Decode(inf_pk).has_value());
    std::vector<unsigned char> inf_sig(96, 0);
    inf_sig[0] = 0xc0;
    BOOST_CHECK(!bls::Signature::Decode(inf_sig).has_value());
    // uncompressed flag (not canonical compressed form)
    std::vector<unsigned char> unc(bytes.begin(), bytes.end());
    unc[0] &= 0x7f;
    BOOST_CHECK(!bls::PublicKey::Decode(unc).has_value());
    // a valid key always round-trips
    const auto again = bls::PublicKey::Decode(bytes);
    BOOST_REQUIRE(again.has_value());
    BOOST_CHECK(*again == pk);
    // secret key bounds: zero and >= r rejected, r-1 accepted
    BOOST_CHECK(!bls::SecretKey::FromBytes(std::vector<unsigned char>(32, 0)).has_value());
    const auto r = HexBytes("73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001");
    BOOST_CHECK(!bls::SecretKey::FromBytes(r).has_value());
    auto r_minus_1 = r;
    r_minus_1[31] = 0x00;
    BOOST_CHECK(bls::SecretKey::FromBytes(r_minus_1).has_value());
    BOOST_CHECK(!bls::SecretKey::FromBytes(std::vector<unsigned char>(31, 1)).has_value());
    BOOST_CHECK(!bls::SecretKey::FromIKM(std::vector<unsigned char>(16, 1)).has_value());
}

BOOST_AUTO_TEST_CASE(pop_and_domain_separation_pinned)
{
    const auto sk = KeyFromIndex(7);
    BOOST_REQUIRE(sk.has_value());
    const bls::PublicKey pk = sk->GetPublicKey();
    const bls::Signature pop = sk->SignPoP();
    BOOST_CHECK(bls::VerifyPoP(pk, pop));
    // Pinned B3 vectors (this wrapper; freezes the PoP behaviour and the IKM key derivation).
    BOOST_CHECK_EQUAL(ToHex(sk->Bytes()), "2ddec4e394f06d1f32ab52da627d71878efa81cef46c55a71959f3d07951c084");
    BOOST_CHECK_EQUAL(ToHex(pk.Compressed()), "ae773189e37b06140fed515bb9b8cbb6e573a7e154761480c12381e0c992b80feeecf78131e41c4c89ac5d13a2e1dc40");
    BOOST_CHECK_EQUAL(ToHex(pop.Compressed()), "aceee35695d2ec39fa2a666bbd43004481af8fb7348bcae251939dee6f3b43d0f708157b475066a54ed04cb49cf9a0e5173e4ecc63bc6586188e44e93d4fb248102c626482ad689f64fbbdf2433cbc48443020e59ca7fee89b6abcfa513441d4");
    // Domain separation: a signature over the compressed key under SIG_DST is NOT a PoP,
    // and a PoP is not a valid signature over the same bytes under SIG_DST.
    const bls::Signature sig_over_pk = sk->Sign(std::span<const unsigned char>(pk.Compressed().data(), 32));
    BOOST_CHECK(!bls::VerifyPoP(pk, sig_over_pk));
    std::array<unsigned char, 32> digest{};
    std::copy(pk.Compressed().begin(), pk.Compressed().begin() + 32, digest.begin());
    BOOST_CHECK(bls::Verify(pk, digest, sig_over_pk));
    BOOST_CHECK(!bls::Verify(pk, digest, pop));
    // Another key's PoP is not this key's PoP.
    const auto other = KeyFromIndex(8);
    BOOST_CHECK(!bls::VerifyPoP(pk, other->SignPoP()));
    BOOST_CHECK(!bls::VerifyPoP(other->GetPublicKey(), pop));
    // VerifiedPublicKey gate
    BOOST_CHECK(bls::VerifiedPublicKey::FromPoP(pk, pop).has_value());
    BOOST_CHECK(!bls::VerifiedPublicKey::FromPoP(pk, other->SignPoP()).has_value());
    // Digest length is enforced.
    BOOST_CHECK(!bls::Verify(pk, std::vector<unsigned char>(31, 0), pop));
}

BOOST_AUTO_TEST_CASE(aggregate_rules_pinned)
{
    std::array<unsigned char, 32> digest{};
    for (size_t i = 0; i < 32; ++i) digest[i] = static_cast<unsigned char>(0xA5 ^ i);
    std::vector<bls::VerifiedPublicKey> keys;
    std::vector<bls::Signature> sigs;
    for (unsigned i = 1; i <= 5; ++i) {
        const auto sk = KeyFromIndex(100 + i);
        BOOST_REQUIRE(sk.has_value());
        const auto vk = bls::VerifiedPublicKey::FromPoP(sk->GetPublicKey(), sk->SignPoP());
        BOOST_REQUIRE(vk.has_value());
        keys.push_back(*vk);
        sigs.push_back(sk->Sign(digest));
    }
    const auto agg = bls::AggregateSignatures(sigs);
    BOOST_REQUIRE(agg.has_value());
    BOOST_CHECK_EQUAL(ToHex(agg->Compressed()), "8373697e45a702e5c8d2c1ec20a32def6ed2a53a0d57a194896c4d3069c553a35944eeea134c689aae3aa9fa6f30f706068a23e6c46bbab0a08302123815eebe8906757489e285fc61bfba71bed6fef9e36485b9c79545b0bf380e8b454ec66e");
    BOOST_CHECK(bls::FastAggregateVerify(keys, digest, *agg));
    // Missing signer, extra key, wrong digest, wrong DST (a PoP), single aggregation.
    std::vector<bls::VerifiedPublicKey> four(keys.begin(), keys.begin() + 4);
    BOOST_CHECK(!bls::FastAggregateVerify(four, digest, *agg));
    auto six = keys;
    six.push_back(*bls::VerifiedPublicKey::FromPoP(KeyFromIndex(200)->GetPublicKey(), KeyFromIndex(200)->SignPoP()));
    BOOST_CHECK(!bls::FastAggregateVerify(six, digest, *agg));
    auto other_digest = digest;
    other_digest[0] ^= 1;
    BOOST_CHECK(!bls::FastAggregateVerify(keys, other_digest, *agg));
    BOOST_CHECK(!bls::FastAggregateVerify(keys, digest, KeyFromIndex(101)->SignPoP()));
    BOOST_CHECK(!bls::FastAggregateVerify({}, digest, *agg));
    const auto one = bls::AggregateSignatures(std::span<const bls::Signature>(sigs.data(), 1));
    BOOST_REQUIRE(one.has_value());
    BOOST_CHECK(*one == sigs[0]);
    BOOST_CHECK(!bls::AggregateSignatures({}).has_value());
    // Aggregating a signature with its own negation would be infinity: we cannot
    // construct a negation through the public API (by design), so the infinity
    // rule is exercised at the decode layer (see decode_rules test).
    // Subset of keys with their subset aggregate verifies.
    const auto agg3 = bls::AggregateSignatures(std::span<const bls::Signature>(sigs.data(), 3));
    std::vector<bls::VerifiedPublicKey> three(keys.begin(), keys.begin() + 3);
    BOOST_CHECK(bls::FastAggregateVerify(three, digest, *agg3));
    BOOST_CHECK(!bls::FastAggregateVerify(keys, digest, *agg3));
}

BOOST_AUTO_TEST_SUITE_END()
