#!/usr/bin/env python3
# Copyright (c) 2026 The B3Coin Core developers
# Distributed under the MIT software license.
"""Capture real Ethereum mainnet sync-committee light-client fixtures.

Emits a C++ header with: genesis_validators_root, the fork schedule, a
light-client bootstrap (trusted root + current committee + branch) and two
LightClientUpdates for consecutive sync-committee periods, so the C++
verifier can be driven through signature verification, finality proofs,
execution-payload proofs and a committee rotation on REAL mainnet data.

Usage: capture_eth_lc_fixture.py [BEACON_URL] > fixture.h
"""
import hashlib
import json
import sys
import urllib.request

API = sys.argv[1] if len(sys.argv) > 1 else "https://ethereum-beacon-api.publicnode.com"


def get(path):
    req = urllib.request.Request(API + path, headers={
        "Accept": "application/json", "User-Agent": "curl/8.7.1"})
    with urllib.request.urlopen(req, timeout=60) as f:
        return json.load(f)


def hx(s):
    return bytes.fromhex(s[2:] if s.startswith("0x") else s)


def h(a, b):
    return hashlib.sha256(a + b).digest()


def u64(v):
    return int(v).to_bytes(8, "little") + b"\x00" * 24


def merk(chunks, depth):
    zero = b"\x00" * 32
    if not chunks:
        for _ in range(depth):
            zero = h(zero, zero)
        return zero
    for _ in range(depth):
        nxt = []
        for i in range(0, len(chunks), 2):
            nxt.append(h(chunks[i], chunks[i + 1] if i + 1 < len(chunks) else zero))
        chunks = nxt
        zero = h(zero, zero)
    return chunks[0]


def header_root(hd):
    return merk([u64(hd["slot"]), u64(hd["proposer_index"]), hx(hd["parent_root"]),
                 hx(hd["state_root"]), hx(hd["body_root"])], 3)


def emit_header(name, hd):
    print(f"inline const BeaconHeaderHex {name}{{{hd['slot']}, {hd['proposer_index']}, "
          f"\"{hx(hd['parent_root']).hex()}\", \"{hx(hd['state_root']).hex()}\", \"{hx(hd['body_root']).hex()}\"}};")


def emit_exec(name, ex):
    base_fee = int(ex["base_fee_per_gas"]).to_bytes(32, "little")
    print(f"inline const ExecHeaderHex {name}{{")
    print(f"    \"{hx(ex['parent_hash']).hex()}\", \"{hx(ex['fee_recipient']).hex()}\", "
          f"\"{hx(ex['state_root']).hex()}\", \"{hx(ex['receipts_root']).hex()}\",")
    print(f"    \"{hx(ex['logs_bloom']).hex()}\",")
    print(f"    \"{hx(ex['prev_randao']).hex()}\", {ex['block_number']}, {ex['gas_limit']}, "
          f"{ex['gas_used']}, {ex['timestamp']},")
    print(f"    \"{hx(ex['extra_data']).hex()}\", \"{base_fee.hex()}\", \"{hx(ex['block_hash']).hex()}\",")
    print(f"    \"{hx(ex['transactions_root']).hex()}\", \"{hx(ex['withdrawals_root']).hex()}\", "
          f"{ex['blob_gas_used']}, {ex['excess_blob_gas']}}};")


def emit_branch(name, roots):
    print(f"inline const std::vector<std::string> {name}{{" +
          ", ".join(f"\"{hx(r).hex()}\"" for r in roots) + "};")


def emit_committee(name, c):
    keys = "".join(hx(k).hex() for k in c["pubkeys"])
    print(f"inline const std::string {name}_PUBKEYS{{\n    \"{keys}\"}};")
    print(f"inline const std::string {name}_AGG{{\"{hx(c['aggregate_pubkey']).hex()}\"}};")


def emit_lc_header(prefix, hd):
    emit_header(prefix + "_BEACON", hd["beacon"])
    emit_exec(prefix + "_EXEC", hd["execution"])
    emit_branch(prefix + "_EXEC_BRANCH", hd["execution_branch"])


def main():
    genesis = get("/eth/v1/beacon/genesis")["data"]
    forks = get("/eth/v1/config/fork_schedule")["data"]
    fin = get("/eth/v1/beacon/headers/finalized")["data"]["header"]["message"]
    period = int(fin["slot"]) // 8192
    start = period - 2
    upd = get(f"/eth/v1/beacon/light_client/updates?start_period={start}&count=2")
    assert len(upd) == 2, f"need 2 updates, got {len(upd)}"
    u1, u2 = upd[0]["data"], upd[1]["data"]
    v1, v2 = upd[0]["version"], upd[1]["version"]

    boot_root = header_root(u1["finalized_header"]["beacon"])
    boot = get(f"/eth/v1/beacon/light_client/bootstrap/0x{boot_root.hex()}")
    bver = boot["version"]
    boot = boot["data"]
    assert header_root(boot["header"]["beacon"]) == boot_root

    sys.stderr.write(f"periods {start},{start+1}; bootstrap root 0x{boot_root.hex()} ({bver}); "
                     f"updates versions {v1},{v2}\n")

    print("// Generated by contrib/b3bridge/capture_eth_lc_fixture.py -- DO NOT EDIT.")
    print(f"// Ethereum mainnet light-client fixture captured from {API}.")
    print(f"// Bootstrap at finalized root 0x{boot_root.hex()} (fork '{bver}'),")
    print(f"// updates for sync-committee periods {start} ('{v1}') and {start+1} ('{v2}').")
    print("#ifndef B3COIN_TEST_DATA_ETH_LC_FIXTURE_H")
    print("#define B3COIN_TEST_DATA_ETH_LC_FIXTURE_H")
    print("#include <cstdint>\n#include <string>\n#include <vector>")
    print("namespace eth_lc_fixture {")
    print("struct BeaconHeaderHex { uint64_t slot; uint64_t proposer_index; std::string parent_root; std::string state_root; std::string body_root; };")
    print("struct ExecHeaderHex { std::string parent_hash; std::string fee_recipient; std::string state_root; std::string receipts_root; std::string logs_bloom; std::string prev_randao; uint64_t block_number; uint64_t gas_limit; uint64_t gas_used; uint64_t timestamp; std::string extra_data; std::string base_fee_le; std::string block_hash; std::string transactions_root; std::string withdrawals_root; uint64_t blob_gas_used; uint64_t excess_blob_gas; };")
    print("struct ForkHex { uint64_t epoch; std::string version; };")
    print(f"inline const std::string GENESIS_VALIDATORS_ROOT{{\"{hx(genesis['genesis_validators_root']).hex()}\"}};")
    print("inline const std::vector<ForkHex> FORKS{" + ", ".join(
        f"{{{int(f['epoch'])}, \"{hx(f['current_version']).hex()}\"}}" for f in forks) + "};")

    print(f"inline const std::string BOOTSTRAP_ROOT{{\"{boot_root.hex()}\"}};")
    emit_header("BOOTSTRAP_BEACON", boot["header"]["beacon"])
    emit_committee("BOOTSTRAP_COMMITTEE", boot["current_sync_committee"])
    emit_branch("BOOTSTRAP_COMMITTEE_BRANCH", boot["current_sync_committee_branch"])

    for i, (u, tag) in enumerate(((u1, "U1"), (u2, "U2"))):
        emit_lc_header(tag + "_ATTESTED", u["attested_header"])
        emit_lc_header(tag + "_FINALIZED", u["finalized_header"])
        emit_branch(tag + "_FINALITY_BRANCH", u["finality_branch"])
        emit_committee(tag + "_NEXT", u["next_sync_committee"])
        emit_branch(tag + "_NEXT_BRANCH", u["next_sync_committee_branch"])
        print(f"inline const std::string {tag}_SYNC_BITS{{\"{hx(u['sync_aggregate']['sync_committee_bits']).hex()}\"}};")
        print(f"inline const std::string {tag}_SYNC_SIG{{\"{hx(u['sync_aggregate']['sync_committee_signature']).hex()}\"}};")
        print(f"inline constexpr uint64_t {tag}_SIGNATURE_SLOT{{{u['signature_slot']}}};")
    print("} // namespace eth_lc_fixture")
    print("#endif")


if __name__ == "__main__":
    main()
