// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {TestBase} from "./TestBase.sol";
import {B3Types} from "../src/IB3FinalityProver.sol";
import {BlsCertificateProver} from "../src/BlsCertificateProver.sol";
import {B3FinalityVerifier} from "../src/B3FinalityVerifier.sol";

/// Post-Fusaka Osaka/EIP-2537 gas bound for the deployment-pinned
/// 64-member bridge cap.
///
/// The binary fixture was generated by B3's vendored blst v0.3.17 from 64
/// distinct deterministic PoP-verified keys. Exactly 43 validators sign (the
/// minimum headcount quorum) and the proof carries all 21 absent validators,
/// including their ordered depth-13 Merkle paths. This is the largest V1
/// absent-witness proof admitted by MAX_PROVEN_BRIDGE_VALIDATORS.
contract BlsCertificateGasBoundTest is TestBase {
    bytes32 private constant CHAIN_DOMAIN = hex"d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0";
    bytes32 private constant SET0_HASH = hex"23c41c0c48be76ff3983e6e94c460de4c67584414d3c89f911c336b31a396d6c";
    bytes32 private constant SET1_HASH = hex"484039e5e8fe8a24c83aa52af44e284f22d5a9d12c2f0053c3ce862c72a6a090";
    bytes32 private constant BOOTSTRAP_SET_HASH = hex"5188225d2e128c1f51a61f4f6bad92dd8da6566549156bae3ebb81728158bf14";
    bytes32 private constant MEMBERS_ROOT = hex"68adb90eed00952dd48e44f440f9f4e0d1be569f944757226883ff3c6a461124";
    bytes32 private constant CERTIFICATE_FIXTURE_SHA256 =
        hex"a77a685dbdc9690877ff34265397a13e4d440a123ea56b6005315b627ae8178e";
    bytes32 private constant BOOTSTRAP_FIXTURE_SHA256 =
        hex"a1f5e2e103c52a9f69595ed0cbea72810a2ec6bc9a49e9efac180660c0182870";

    uint256 private constant EXPECTED_PROOF_BYTES = 18_144;
    uint256 private constant EXPECTED_BOOTSTRAP_PROOF_BYTES = 1_504;
    uint256 private constant EIP7825_TRANSACTION_GAS_CAP = 16_777_216;

    bytes private constant AGGREGATE_PUBLIC_KEY =
        hex"936e276e891a36681c10868bd616382743a374877d4e36f1fb508c40122885f81cfb75e0395547819b94e35caff5e76e";
    bytes private constant BOOTSTRAP_AGGREGATE_PUBLIC_KEY =
        hex"afea1502f003a9ab0d8bf89c1826bc78d3e01413f9e78e836b0b99dba05c3ce5d9e81f1478697a4d776aeee83449ec54";
    bytes32 private constant BOOTSTRAP_MEMBERS_ROOT =
        hex"78621e43cecacca419e7d29cb7458f31262616dce6083cf3f32ddec1b67b5910";

    event WorstCaseGasBound(
        uint256 proofBytes, uint256 submitCalldataBytes, uint256 submitExecutionGas, uint256 conservativeTotalGas
    );

    function test_Maximum64MemberAbsentWitnessFitsTransactionGasCap() public {
        bytes memory proof = vm.readFileBinary("test/vectors/bls64_proof.bin");
        bytes memory bootstrapProof = vm.readFileBinary("test/vectors/bls64_bootstrap_proof.bin");
        assertEq(proof.length, EXPECTED_PROOF_BYTES);
        assertEq(bootstrapProof.length, EXPECTED_BOOTSTRAP_PROOF_BYTES);
        assertEq(sha256(proof), CERTIFICATE_FIXTURE_SHA256);
        assertEq(sha256(bootstrapProof), BOOTSTRAP_FIXTURE_SHA256);

        B3Types.FinalizedBlock memory finalizedBlock = _finalizedBlock();
        B3Types.SetHeader memory signingSet = _set(0);
        B3Types.SetHeader memory successor = _set(1);
        assertEq(B3Types.hashSetHeader(signingSet), SET0_HASH);
        assertEq(B3Types.hashSetHeader(successor), SET1_HASH);

        BlsCertificateProver prover = new BlsCertificateProver();
        B3Types.SetHeader memory bootstrap = _bootstrapSet();
        B3FinalityVerifier verifier = new B3FinalityVerifier(
            CHAIN_DOMAIN,
            bootstrap,
            BOOTSTRAP_SET_HASH,
            prover,
            address(prover).codehash,
            B3FinalityVerifier.DeploymentConfig({
                modernStartHeight: 811_001,
                bridgeActivationHeight: 811_001,
                minBridgeValidators: 4,
                maxBridgeValidators: 64,
                minBridgeTotalWeight: 1,
                minEpochDuration: 1 days,
                maxEpochLag: 30 days,
                maxCertificateAge: 1 days,
                minDepositExitWindow: 1 days,
                bootstrapDeadline: block.timestamp + 7 days
            })
        );
        verifier.initialize(_snapshot(), signingSet, bootstrapProof);

        uint256 gasBefore = gasleft();
        verifier.submitCertificate(finalizedBlock, successor, proof);
        uint256 submitExecutionGas = gasBefore - gasleft();
        assertEq(verifier.nextSetHash(), SET1_HASH);
        assertEq(verifier.latestBridgeWithdrawalRoot(), finalizedBlock.withdrawalRoot);
        assertTrue(verifier.bridgeReady());

        // Exact top-level transaction calldata for the successfully executed
        // production verifier call above.
        bytes memory submitCalldata =
            abi.encodeWithSelector(B3FinalityVerifier.submitCertificate.selector, finalizedBlock, successor, proof);

        // EIP-7623's calldata floor prices a non-zero byte at 40 gas. Treating
        // every byte as non-zero is conservative. The measured call already
        // includes verifier checks, the prover, storage, and event emission.
        uint256 conservativeTotalGas = 21_000 + submitCalldata.length * 40 + submitExecutionGas;
        emit WorstCaseGasBound(proof.length, submitCalldata.length, submitExecutionGas, conservativeTotalGas);
        assertTrue(conservativeTotalGas < EIP7825_TRANSACTION_GAS_CAP);
    }

    function _finalizedBlock() private pure returns (B3Types.FinalizedBlock memory finalizedBlock) {
        finalizedBlock.height = 811_001;
        finalizedBlock.epoch = 0;
        finalizedBlock.blockHash = hex"0101010101010101010101010101010101010101010101010101010101010101";
        finalizedBlock.withdrawalRoot = hex"0202020202020202020202020202020202020202020202020202020202020202";
        finalizedBlock.validatorSetHash = SET1_HASH;
    }

    function _snapshot() private pure returns (B3Types.FinalizedBlock memory snapshot) {
        snapshot.height = 811_000;
        snapshot.epoch = 0;
        snapshot.blockHash = hex"1111111111111111111111111111111111111111111111111111111111111111";
        snapshot.withdrawalRoot = bytes32(0);
        snapshot.validatorSetHash = SET0_HASH;
    }

    function _set(uint64 epoch) private pure returns (B3Types.SetHeader memory signingSet) {
        signingSet.epoch = epoch;
        signingSet.rulesetVersion = 1;
        signingSet.validatorCount = 64;
        signingSet.totalWeight = 64;
        signingSet.quorumWeight = 43;
        signingSet.aggregatePubkey = AGGREGATE_PUBLIC_KEY;
        signingSet.membersRoot = MEMBERS_ROOT;
    }

    function _bootstrapSet() private pure returns (B3Types.SetHeader memory bootstrap) {
        bootstrap.epoch = 0;
        bootstrap.rulesetVersion = 1;
        bootstrap.validatorCount = 4;
        bootstrap.totalWeight = 4;
        bootstrap.quorumWeight = 3;
        bootstrap.aggregatePubkey = BOOTSTRAP_AGGREGATE_PUBLIC_KEY;
        bootstrap.membersRoot = BOOTSTRAP_MEMBERS_ROOT;
    }
}
